[package]
name = "monero-rpc"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
repository = "https://github.com/monero-ecosystem/monero-rpc-rs"
edition = "2018"
license = "MIT OR Apache-2.0"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
chrono = { version = "*", features = ["serde"] }
failure = "*"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
fixed-hash = "0.3"
hex = { git = "https://github.com/KokaKiwi/rust-hex" }
jsonrpc-core = "*"
log = "*"
monero = { git = "https://github.com/monero-rs/monero-rs", features = ["serde"] }
reqwest = "*"
rustc-hex = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "*"
uuid = { version = "*", features = ["v4"] }
