[package]
name = "monero-rpc"
description = "RPC client for Monero daemon and wallet"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
repository = "https://github.com/monero-ecosystem/monero-rpc-rs"
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["asynchronous", "net"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
futures-preview = "0.3.0-alpha.18"
fixed-hash = "0.3"
headers = "*"
hex = "0.3"
http = "*"
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
jsonrpc-core = "12.0"
log = "*"
monero = { version = "0.2", features = ["serde"] }
rustc-hex = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4"] }
